### ISSUE TITLE
For RHEL 9 on ppc64le, an ifcfg-(interface) file might not exist

### ISSUE THREAD

**Issue by berndfinger** [linux-system-roles/sap-hana-preconfigure#194]
... in /etc/sysconfig/network-scripts. So let's better ignore errors in task "Add largesend options to interfaces".

**Comment by richm** [comment]
in rhel9, the ifcfg / initscript method of configuring network is going away - @cathay4t

**Comment by berndfinger** [comment]
Closing after copying over to https://github.com/sap-linuxlab/community.sap_install/issues/18
