### ISSUE TITLE
check if reboot is required (7.3+)

### ISSUE THREAD

**Issue by tbludau** [linux-system-roles/sap-hana-preconfigure#2]
Integration of check if reboot is required (7.2) and check if reboot is required (7.3+) are not compatible with each other.

Here are two variables registred with one name. This will not work, because i got everytime the output (variable reboot_required) of the last task, and for a rhel 7.4 system this is a empty variable.
(Changed the register variable to reboot_required_72 before, but this is only much more complex.)

Also i commented the broken passage. Not tested with a rhel 7.2

**Comment by rhmk** [comment]
Agree, so reboot 7.2 always is fine for me.
