### ISSUE TITLE
Remove module ansible.posix.selinux

### ISSUE THREAD

**Issue by berndfinger** [linux-system-roles/sap-hana-preconfigure#200]
Affected task: "Set SELinux state" in line 6 of tasks/RedHat/generic/disable-selinux.yml

**Comment by pcahyna** [comment]
I am curious why do you want to remove it (I suppose the call) - what's wrong with it?

**Comment by berndfinger** [comment]
See also https://github.com/linux-system-roles/sap-hana-preconfigure/issues/163 .
