### ISSUE TITLE
Remove module ansible.posix.sysctl

### ISSUE THREAD

**Issue by berndfinger** [linux-system-roles/sap-hana-preconfigure#201]
Affected tasks:
- "Add largesend kernel parameters for ppc64le" in line 57 of tasks/sapnote/2055470.yml
- "setting kernel tunables as per SAP note 2382421" in line 9 of tasks/sapnote/2382421.yml
- "Set kernel tunables as per SAP note 3024346" in line 9 of tasks/sapnote/3024346.yml
- "Set kernel parameter kernel.pid_max to 4194304" in line 6 of tasks/sapnote/2777782/10-increase-pidmax.yml

**Comment by pcahyna** [comment]
What do you want to replace it with - using the kernel_settings role instead?

**Comment by berndfinger** [comment]
No, I need to follow the SAP notes. These currently demand to set parameters in specific files (e.g. /etc/sysctl.d/sap_hana.conf). So I will use Ansible modules for modifying files (e.g. lineinfile).

**Comment by pcahyna** [comment]
You could probably use the `sysctl_file` parameter of the module:

https://docs.ansible.com/ansible/latest/collections/ansible/posix/sysctl_module.html#parameter-sysctl_file
