### ISSUE TITLE
Role is not recognizing cloud eus/e4s repositories

### ISSUE THREAD

**Issue by Klaas-** [linux-system-roles/sap-hana-preconfigure#56]
https://github.com/linux-system-roles/sap-hana-preconfigure/blob/32426d45de0ac9f846f8534d4e1b4322c1f8f43c/tasks/sapnote/2009879.yml#L10-L18

repos are named like this:
rhui-rhel-7-server-rhui-eus-rpms
rhel-sap-for-rhel-7-server-eus-rhui-rpms
rhui-sap-hana-for-rhel-7-server-eus-rpms

**Comment by rhmk** [comment]
Thanks, the role just prints an error, but ignores it. So it safe to use it. Thanks for pointing that out.
We do not do a hard check for the repositories, as some customers even do a reposync and name it completely different.
So we can add this for Azure (and other CCSPs for checking as well)

**Comment by berndfinger** [comment]
The role now has four user variables in defaults/main.yml which can be used to define required repos for RHEL 7 and RHEL 8. Please let me know if this covers your request.

**Comment by berndfinger** [comment]
Development and maintenance of this software has stopped. The role [sap_hana_preconfigure](https://github.com/sap-linuxlab/community.sap_install/tree/main/roles/sap_hana_preconfigure) replaces it. I am closing this issue now as per my last reply. Feel free to create a new issue if my proposal and reply did not solve your issue.
