### ISSUE TITLE
feature idea: moving reboot to after all configuration changes

### ISSUE THREAD

**Issue by Klaas-** [linux-system-roles/sap-hana-preconfigure#59]
https://github.com/linux-system-roles/sap-hana-preconfigure/blob/master/tasks/RedHat/generic/disable-thp.yml#L18
currently if you modify the grub config the system does not get rebooted. I suggest the reboot should be moved to the end of the role and to run `meta: flush_handlers` before reboot. This could also mean we'd need to move some of the checks to after the reboot, I only skimmed over them.

**Comment by berndfinger** [comment]
Thanks. Will certainly do this, see my comments to https://github.com/linux-system-roles/sap-hana-preconfigure/issues/55 .
