### ISSUE TITLE
handler: regenerate grub2 conf not working on ansible 2.8

### ISSUE THREAD

**Issue by Klaas-** [linux-system-roles/sap-hana-preconfigure#60]
$ ansible --version
ansible 2.8.3

I think it needs to be `include_tasks: tasks/RedHat/generic/regenerate-grub2-conf.yml`; I'll pr it

**Comment by berndfinger** [comment]
Thanks. See my comments to https://github.com/linux-system-roles/sap-hana-preconfigure/pull/61 .

**Comment by berndfinger** [comment]
Solved in pull request #82 .
