### ISSUE TITLE
reboot fails on RHEL 8

### ISSUE THREAD

**Issue by rhmk** [linux-system-roles/sap-hana-preconfigure#67]
the command needs-rebooting is not executed on RHEL 8, hence if you set the variable sap_hana_preconfigure_reboot_after_update == true
the playbook fails.
Required fix:
- add yum-utils to the list of required packages (not installed by default)
- change the when statement to   ansible_distribution_major_version >=7 in task "check if reboot is required (7.3+)"

**Comment by rhmk** [comment]
The command needs-restarting is part of the package yum-utils, which is not in the list of required packages (i.e.@base or @server) This command is used to check if a reboot of the server is required. Hence yum-utils is added to the list of required packages.

This command is used in the module "check if reboot is required (7.3+)"
Currently this module is only executed on RHEL7, so the when statement is changed accordingly.
If the command is not installed this module fails.

If the module named "check if reboot is required (7.3+)" is skipped the according variable "sap_hana_preconfigure_register_reboot_required" is not set.
If the default value of "sap_hana_preconfigure_reboot_after_update" is changed to true and sap_hana_preconfigure_register_reboot_required is not set the playbook will fail with unset variable.

**Comment by rhmk** [comment]
Patches are submitted against berndfingers fork

**Comment by berndfinger** [comment]
See https://github.com/berndfinger/sap-preconfigure/blob/4a1f8c15991a4c8369ab56f7c457c49a96e76bcb/tasks/installation.yml . I tested using the environment groups as demanded in SAP notes 2002167 and 2772999. For RHEL 8, I am using "yum needs-restarting -r". For RHEL 7, I am using "needs-restarting -r".
