### ISSUE TITLE
RHEL 8 PPCLE Packages

### ISSUE THREAD

**Issue by rhmk** [linux-system-roles/sap-hana-preconfigure#68]
The follwoing packages are required for ppcle on Power 9

yum install librtas src rsct.core.utils rsct.core rsct.basic rsct.opt.storagerm \
                 devices.chrp.base.ServiceRM DynamicRM ncurses-libs readline sqlite  \
                 sg3_utils libgcc libstdc++ zlib iprutils lsvpd libvpd libservicelog \
                 servicelog powerpc-utils ppc64-diag IBMinvscout

They are currently disabled in the role, as they were not available during test. They are now available via:
https://public.dhe.ibm.com/software/server/POWER/Linux/yum/OSS/RHEL/8/ppc64le/

valid for  RHEL8.0 and 8.1

**Comment by berndfinger** [comment]
Solved in pull request #82 .
