### ISSUE TITLE
update_only is not a valid parameter for package module

### ISSUE THREAD

**Issue by piluxh** [linux-system-roles/sap-hana-preconfigure#71]
"update_only: true" is not a valid parameter to the "package" module in RedHat/installation.yml

**Comment by berndfinger** [comment]
Thanks for this. As per https://docs.ansible.com/ansible/latest/modules/yum_module.html , "When using latest, only update installed packages. Do not install packages.
Has an effect only if state is latest". So I will probably remove this line.
See also https://github.com/berndfinger/sap-preconfigure/blob/4a1f8c15991a4c8369ab56f7c457c49a96e76bcb/tasks/installation.yml .

**Comment by berndfinger** [comment]
Oops - let's keep this open until solved.

**Comment by berndfinger** [comment]
Solved in pull request #82 .
