### ISSUE TITLE
required for update and reboot

### ISSUE THREAD

**Issue by rhmk** [linux-system-roles/sap-hana-preconfigure#72]
The test for updating is failing. rc is not defined:
See output:
TASK [sap-hana-preconfigure : restart machine if required] *********************

fatal: [dhcp168.coe.muc.redhat.com]: FAILED! => {"msg": "The conditional check 'sap_hana_preconfigure_reboot_after_update == true and sap_hana_preconfigure_register_reboot_required.rc == 1' failed. The error was: error while evaluating conditional (sap_hana_preconfigure_reboot_after_update == true and sap_hana_preconfigure_register_reboot_required.rc == 1): 'dict object' has no attribute 'rc'\n\nThe error appears to be in '/usr/share/ansible/roles/sap-hana-preconfigure/tasks/RedHat/installation.yml': line 85, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      # inspired by https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back\n      - name: restart machine if required\n        ^ here\n"}

...ignoring

TASK [sap-hana-preconfigure : waiting for server to come back] *****************

fatal: [dhcp168.coe.muc.redhat.com]: FAILED! => {"msg": "The conditional check 'sap_hana_preconfigure_reboot_after_update == true and sap_hana_preconfigure_register_reboot_required.rc == 1' failed. The error was: error while evaluating conditional (sap_hana_preconfigure_reboot_after_update == true and sap_hana_preconfigure_register_reboot_required.rc == 1): 'dict object' has no attribute 'rc'\n\nThe error appears to be in '/usr/share/ansible/roles/sap-hana-preconfigure/tasks/RedHat/installation.yml': line 92, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n      - name: waiting for server to come back\n        ^ here\n"}

PLAY RECAP *********************************************************************
dhcp168.coe.muc.redhat.com : ok=11   changed=1    unreachable=0    failed=1    skipped=2    rescued=0    ignored=1
422 Client Error: Unprocessable Entity

**Comment by berndfinger** [comment]
Do we really have to reboot in between? I'd rather not reboot in the role itself at all but let the role fail if a reboot is required. Then the rebooting can be done in the playbook which is calling the role. See also the code in https://github.com/berndfinger/sap-preconfigure/blob/4a1f8c15991a4c8369ab56f7c457c49a96e76bcb/tasks/installation.yml .

**Comment by berndfinger** [comment]
Solved in pull request #82 .
