### ISSUE TITLE
uninstall  HANA and remove all configuration

### ISSUE THREAD

**Issue by alexxa** [linux-system-roles/sap-hana-preconfigure#93]
As a user, I would appreciate an option to remove all configuration for HANA and uninstall it, in other words clean up the environment. 

If this option exists, add it to Readme, please.

**Comment by pcahyna** [comment]
As this role does not install HANA, does it make sense for the role to uninstall it?

**Comment by rickgcv** [comment]
@alexxa That is something that would make more sense to include in https://github.com/redhat-sap/sap-hana-deployment feel free to open an issue there.

**Comment by alexxa** [comment]
@pcahyna Maybe I was mistaken by "you can limit the scope of the role to only execute the installation" Readme line.  =) 

Still, this preconfigure role creates a user, enables certain repos, installs pkgs, etc. 
Do you think there is no user case to undo it all? 

I will open an issue on  https://github.com/redhat-sap/sap-hana-deployment too. Thanks @rickgcv

**Comment by berndfinger** [comment]
@alexxa Besides uninstalling HANA, do you think it would be useful to revert to the configuration before the role has been run? In that case, we should discuss if it's not easier and faster to reinstall the system from a backup or (much more likely) from the installation media. Reverting to the previous configuration could make sense if the role is to be used on a system which has production software running and maybe has already been configured. But such a case is explicitly mentioned in the README.md as not being supported.

**Comment by berndfinger** [comment]
In addition, we do not want the roles to be able to destroy an SAP landscape. The risk of unintended loss of data would be too high. If there is a demand for a role which cleans up an SAP deployment or reverts system settings for SAP to default RHEL system settings, this should be done in a separate role.
